In [118]:
import numpy as np
import pandas as pd

In [119]:
a = [1,2,3,4,5,6]

In [120]:
s = pd.Series(a)

In [121]:
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [122]:
d = {"Aman":68,"Rohan":50,"Uttam":90}
s = pd.Series(d)

In [123]:
s

Aman     68
Rohan    50
Uttam    90
dtype: int64

In [124]:
df = pd.DataFrame([d])

In [125]:
df

   Aman  Rohan  Uttam
0    68     50     90

In [126]:
 pd.DataFrame({
    "name": ["Aman", "Riya"],
    "salary": [40000, 65000]
})

   name  salary
0  Aman   40000
1  Riya   65000

In [127]:
# list of dictionaries — one dict per row
pd.DataFrame([
    {"name": "Aman", "salary": 40000},
    {"name": "Riya", "salary": 65000}
])

   name  salary
0  Aman   40000
1  Riya   65000

In [128]:
import numpy as np
import pandas as pd

In [129]:
df = pd.read_csv("employees_100.csv")

In [130]:
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [131]:
df.head() #first five rows are print

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [132]:
df.tail() #Last five rows are print

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [133]:
df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
16,177,Vivek Malhotra,Finance,Bangalore,NaN,NaN,3,4,12,2021-09-12

In [134]:
df.shape

(100, 10)

In [135]:
df.dtypes

employee_id             int64
name                   object
department             object
city                   object
age                   float64
salary                 object
experience              int64
performance_score       int64
projects_completed      int64
joining_date           object
dtype: object

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    object
 2   department          92 non-null     object
 3   city                90 non-null     object
 4   age                 94 non-null     float64
 5   salary              92 non-null     object
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 7.9+ KB

In [137]:
df.describe()

,employee_id,age,experience,performance_score,projects_completed
count,100.000000,94.000000,100.000000,100.0000,100.000000
mean,148.740000,30.861702,4.830000,5.7500,9.970000
std,27.420637,6.483397,3.755279,1.7019,5.332301
min,101.000000,22.000000,0.000000,2.0000,0.000000
25%,125.750000,25.250000,2.000000,5.0000,6.000000
50%,149.500000,31.000000,4.500000,6.0000,9.500000
75%,171.250000,35.750000,8.000000,7.0000,13.250000
max,196.000000,45.000000,17.000000,10.0000,24.000000

In [138]:
df.isnull()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,True,False,False,False,False
98,False,False,False,True,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False

In [139]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [140]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [141]:
df['salary']

0     70719
1     77058
2     69911
3     69993
4     88216
      ...
95    55740
96    52250
97      NaN
98    56821
99    69499
Name: salary, Length: 100, dtype: object

In [142]:
df[["name",'salary']]

              name salary
0     Swati Kapoor  70719
1   Kavya Malhotra  77058
2     Manish Desai  69911
3         Neha Das  69993
4        Isha Nair  88216
..             ...    ...
95     Nikhil Nair  55740
96      Neha Desai  52250
97      Neha Reddy    NaN
98     Priya Nayak  56821
99     Kavya Joshi  69499

[100 rows x 2 columns]

In [143]:
df = df.set_index("employee_id")

In [144]:
df.head()

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [145]:
df.loc[184]

name                  Swati Kapoor
department            Data Science
city                       Kolkata
age                           38.0
salary                       70719
experience                       5
performance_score                5
projects_completed               6
joining_date            2021-07-02
Name: 184, dtype: object

In [146]:
df.loc[[184,145]]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [147]:
df.loc[184:145]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [148]:
df.iloc[0]

name                  Swati Kapoor
department            Data Science
city                       Kolkata
age                           38.0
salary                       70719
experience                       5
performance_score                5
projects_completed               6
joining_date            2021-07-02
Name: 184, dtype: object

In [149]:
df.iloc[0:10]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
181,Karan Rao,Marketing,NaN,22.0,50733,1,6,6,2020-04-05
111,Kavya Singh,Engineering,Delhi,23.0,NaN,1,5,10,2021-09-14
101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21

In [150]:
df.loc[154:145][["name","city","age","salary"]]

                       name       city   age salary
employee_id
154          Kavya Malhotra     Mumbai   NaN  77058
171            Manish Desai  Hyderabad  23.0  69911
146                Neha Das       Pune  28.0  69993
145               Isha Nair        NaN  32.0  88216

In [151]:
df.iloc[1:5][["name","city","age","salary"]]

                       name       city   age salary
employee_id
154          Kavya Malhotra     Mumbai   NaN  77058
171            Manish Desai  Hyderabad  23.0  69911
146                Neha Das       Pune  28.0  69993
145               Isha Nair        NaN  32.0  88216

In [152]:
df[df['projects_completed']>10]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
119,Ritu Desai,Marketing,Pune,22.0,55321,0,6,18,2020-02-18
131,Priya Malhotra,Marketing,Hyderabad,25.0,55295,1,7,12,2022-02-13
174,Divya Chatterjee,Finance,Kolkata,24.0,58374,1,3,12,2018-09-21
134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,12,2021-11-24
191,Neha Malhotra,Marketing,Mumbai,29.0,64944,2,10,18,2023-10-05
177,Vivek Malhotra,Finance,Bangalore,NaN,NaN,3,4,12,2021-09-12
132,Swati Malhotra,Engineering,Chennai,33.0,77222,5,7,15,2018-10-09
189,Anjali Shah,Marketing,Delhi,33.0,56321,6,7,14,2022-08-14
143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15
141,Manish Kulkarni,HR,Chennai,27.0,"45,835",3,8,13,2022-07-21
162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,6,11,2020-09-05
148,Kavya Nair,Engineering,Chennai,NaN,"76,320",3,7,11,2024-03-07
106,Vivek Singh,HR,Delhi,27.0,56886,3,6,11,2020-08-04
166,Meera Nayak,HR,Hyderabad,33.0,56940,4,7,13,2023-04-14
117,Pooja Malhotra,engineering,Kolkata,24.0,84255,1,8,19,2021-12-05
196,Sanjay Pillai,Marketing,Bangalore,NaN,60503,0,8,15,2022-11-08
120,Isha Gupta,Marketing,Mumbai,26.0,NaN,6,5,14,2018-03-27
182,Pooja Reddy,Sales,Delhi,34.0,63700,7,6,14,2019-12-28
104,Ritu Iyer,Marketing,Bangalore,34.0,63574,8,7,20,2021-05-10
139,Rahul Malhotra,Marketing,Hyderabad,23.0,60203,2,6,15,2022-09-17
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
190,Swati Bose,Data Science,Mumbai,22.0,78465,0,8,18,2022-11-22
144,Arjun Nayak,Engineering,Kolkata,38.0,75226,7,6,17,2019-12-27
168,Sanjay Kulkarni,Engineering,Delhi,34.0,80358,7,5,14,2020-04-01
169,Swati Chatterjee,HR,Pune,33.0,49801,3,6,11,2021-08-20
162,Suresh Chatterjee,HR,Hyderabad,32.0,59273,5,7,11,2020-09-05
134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,13,2021-11-24
159,Rohan Menon,HR,Pune,26.0,56141,3,4,13,2023-01-03
158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,5,19,2021-02-26
158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,6,17,2021-02-26
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18
130,Arjun Nair,Finance,Pune,22.0,60514,0,9,24,2019-06-17
102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
122,Ashok Shah,HR,Hyderabad,31.0,55756,5,8,11,2024-05-11
192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10
183,Deepak Nayak,Marketing,Hyderabad,28.0,62393,2,5,13,2020-08-09
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07

In [153]:
df[df['age']>40]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07
155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [154]:
#give me people who are working in the finance and there age is greater than 30

In [155]:
df[df['department']=='Finance']

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
174,Divya Chatterjee,Finance,Kolkata,24.0,58374,1,3,12,2018-09-21
134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,12,2021-11-24
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
112,Aditya Reddy,Finance,NaN,31.0,58811,2,3,3,2020-05-26
118,Rajesh Nair,Finance,Hyderabad,26.0,67464,1,5,9,2019-01-26
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
151,Sneha Verma,Finance,Delhi,NaN,66422,5,6,5,2023-09-02
134,Vivek Kulkarni,Finance,Kolkata,24.0,59422,3,6,13,2021-11-24
180,Ashok Kulkarni,Finance,Kolkata,31.0,58777,3,5,9,2024-07-10
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
160,Shreya Singh,Finance,Pune,38.0,62020,5,5,0,2019-05-11
138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18
130,Arjun Nair,Finance,Pune,22.0,60514,0,9,24,2019-06-17
153,Pooja Das,Finance,Mumbai,27.0,64112,1,4,6,2019-08-25

In [156]:
df[(df['department']=="Finance") & (df['age']>30)]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
112,Aditya Reddy,Finance,NaN,31.0,58811,2,3,3,2020-05-26
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
180,Ashok Kulkarni,Finance,Kolkata,31.0,58777,3,5,9,2024-07-10
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
160,Shreya Singh,Finance,Pune,38.0,62020,5,5,0,2019-05-11
138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18

In [157]:
df[((df['department']=="Finance") |(df['department']=="Sales"))&(df['age']>30)& (df['experience']>5)]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15
182,Pooja Reddy,Sales,Delhi,34.0,63700,7,6,14,2019-12-28
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18
103,Ananya Nayak,Sales,Delhi,38.0,68490,9,6,6,2021-11-19

In [158]:
df[df["name"].str.contains("Verma")]                        # text search

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
127,Suresh Verma,Data Science,Bangalore,27.0,"72,862",2,6,10,2023-02-21
116,Rohan Verma,Engineering,Chennai,23.0,62693,0,4,8,2018-08-17
110,Arjun Verma,Marketing,Pune,29.0,62227,4,7,8,2022-04-05
151,Sneha Verma,Finance,Delhi,NaN,66422,5,6,5,2023-09-02
147,Tanvi Verma,Engineering,Bangalore,35.0,77217,8,3,0,2022-04-22
133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
188,Sanjay Verma,HR,Bangalore,33.0,59591,8,4,4,2019-03-05
192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10

In [159]:
df.isnull().sum()

name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [160]:
df.dropna()

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
...,...,...,...,...,...,...,...,...,...
183,Deepak Nayak,Marketing,Hyderabad,28.0,62393,2,5,13,2020-08-09
121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [161]:
df2 = df.dropna()

In [162]:
df2.isnull().sum()

name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [163]:
df.dropna(subset = ['city'])

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
...,...,...,...,...,...,...,...,...,...
121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [164]:
df.dropna(subset = ['city',"age"])

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
...,...,...,...,...,...,...,...,...,...
121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [165]:
df['age'].fillna(df['age'].mean())

employee_id
184    38.000000
154    30.861702
171    23.000000
146    28.000000
145    32.000000
         ...
161    22.000000
172    22.000000
115    43.000000
193    23.000000
152    44.000000
Name: age, Length: 100, dtype: float64

In [166]:
df['age'].fillna(df['age'].mean(),inplace = True)

/tmp/ipykernel_535/240904280.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace = True)

In [167]:
df.isnull().sum()

name                   0
department             8
city                  10
age                    0
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [168]:
df['salary'] = df['salary'].str.replace(",","", regex=False)
df['salary'] = pd.to_numeric(df['salary'],errors = 'coerce')
df['salary'] = df['salary'].fillna(df['salary'].median())

In [169]:
df['salary'].dtype

dtype('float64')

In [170]:
df.isnull().sum()

name                   0
department             8
city                  10
age                    0
salary                 0
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [171]:
df['department'].value_counts()

department
HR              17
Marketing       17
Finance         16
Engineering     14
Data Science    10
Sales            8
engineering      3
 HR              2
 Marketing       1
 Finance         1
FINANCE          1
SALES            1
MARKETING        1
Name: count, dtype: int64

In [172]:
df['department'] = df['department'].fillna(df['department'].mode()[0])

In [173]:
df['city'] = df['city'].fillna(df['city'].mode()[0])

In [174]:
df.isnull().sum()

name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [175]:
df.duplicated().sum()

np.int64(0)

In [176]:
df = df.reset_index()

In [177]:
df.duplicated(subset = ["employee_id"]).sum()

np.int64(4)

In [178]:
df.drop_duplicates(subset = ["employee_id"],keep = "first",inplace = True)

In [179]:
df["joining_date"] = pd.to_datetime(df["joining_date"])

In [180]:
df['annual_salary'] = df['salary']*12

In [181]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,848628.0
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,838932.0
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,839916.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0

In [182]:
df['salary'] = df['salary']*12

In [183]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,848628.0,5,5,6,2021-07-02,848628.0
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,838932.0,0,6,18,2019-04-24,838932.0
3,146,Neha Das,Engineering,Pune,28.000000,839916.0,3,8,1,2022-12-13,839916.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0

In [184]:
def categorize(num):
  if num>5:
    return "Experience candicate"
  elif num<=5:
    return "Learner"

In [185]:
df['experience_status'] = df['experience'].apply(categorize)

In [186]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,848628.0,5,5,6,2021-07-02,848628.0,Learner
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0,Learner
2,171,Manish Desai,Data Science,Hyderabad,23.000000,838932.0,0,6,18,2019-04-24,838932.0,Learner
3,146,Neha Das,Engineering,Pune,28.000000,839916.0,3,8,1,2022-12-13,839916.0,Learner
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0,Experience candicate

In [187]:
#lambda function
df["salary_level"] = df["salary"].apply(lambda salary: "High" if salary > 70000 else "Normal")

In [188]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_level
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,848628.0,5,5,6,2021-07-02,848628.0,Learner,High
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0,Learner,High
2,171,Manish Desai,Data Science,Hyderabad,23.000000,838932.0,0,6,18,2019-04-24,838932.0,Learner,High
3,146,Neha Das,Engineering,Pune,28.000000,839916.0,3,8,1,2022-12-13,839916.0,Learner,High
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0,Experience candicate,High

In [189]:
#map function

In [190]:
department_codes = {"Engineering":"ENG", "Marketing":"MKT","Finance":"FIN"}
df["department_code"] = df["department"].map(department_codes)

In [191]:
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_level,department_code
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,848628.0,5,5,6,2021-07-02,848628.0,Learner,High,NaN
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0,Learner,High,NaN
2,171,Manish Desai,Data Science,Hyderabad,23.000000,838932.0,0,6,18,2019-04-24,838932.0,Learner,High,NaN
3,146,Neha Das,Engineering,Pune,28.000000,839916.0,3,8,1,2022-12-13,839916.0,Learner,High,ENG
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0,Experience candicate,High,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.000000,668880.0,0,5,22,2020-04-22,668880.0,Learner,High,NaN
96,172,Neha Desai,HR,Chennai,22.000000,627000.0,0,5,7,2020-11-14,627000.0,Learner,High,NaN
97,115,Neha Reddy,Marketing,Chennai,43.000000,755634.0,12,4,10,2019-06-06,755634.0,Experience candicate,High,MKT
98,193,Priya Nayak,HR,Hyderabad,23.000000,681852.0,3,9,16,2019-08-07,681852.0,Learner,High,NaN
99,152,Kavya Joshi,Marketing,Delhi,44.000000,833988.0,10,7,4,2022-03-25,833988.0,Experience candicate,High,MKT

In [192]:
#Sorting & Ranking

In [193]:
df.sort_values(by = "employee_id")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_level,department_code
9,101,Ananya Malhotra,engineering,Hyderabad,24.000000,823092.0,2,8,0,2023-10-21,823092.0,Learner,High,NaN
84,102,Rahul Menon,Engineering,Hyderabad,38.000000,1018440.0,11,6,15,2021-06-07,1018440.0,Experience candicate,High,ENG
87,103,Ananya Nayak,Sales,Delhi,38.000000,821880.0,9,6,6,2021-11-19,821880.0,Experience candicate,High,NaN
51,104,Ritu Iyer,Marketing,Bangalore,34.000000,762888.0,8,7,20,2021-05-10,762888.0,Experience candicate,High,MKT
15,105,Vivek Pillai,Engineering,Pune,39.000000,755634.0,9,4,5,2024-06-05,755634.0,Experience candicate,High,ENG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,192,Divya Verma,HR,Delhi,40.000000,796356.0,12,7,13,2022-09-10,796356.0,Experience candicate,High,NaN
98,193,Priya Nayak,HR,Hyderabad,23.000000,681852.0,3,9,16,2019-08-07,681852.0,Learner,High,NaN
34,194,Pooja Menon,Engineering,Chennai,30.861702,915372.0,7,4,9,2022-07-28,915372.0,Experience candicate,High,ENG
78,195,Pooja Nair,Finance,Hyderabad,33.000000,832752.0,6,6,4,2023-01-13,832752.0,Experience candicate,High,FIN
43,196,Sanjay Pillai,Marketing,Bangalore,30.861702,726036.0,0,8,15,2022-11-08,726036.0,Learner,High,MKT

In [194]:
df.sort_values(by = "salary")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_level,department_code
26,141,Manish Kulkarni,HR,Chennai,27.0,550020.0,3,8,13,2022-07-21,550020.0,Learner,High,NaN
36,167,Meera Malhotra,HR,Hyderabad,31.0,585864.0,4,5,4,2022-06-24,585864.0,Learner,High,NaN
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,596316.0,0,4,7,2018-08-27,596316.0,Learner,High,MKT
67,169,Swati Chatterjee,HR,Pune,33.0,597612.0,3,6,11,2021-08-20,597612.0,Learner,High,NaN
7,181,Karan Rao,Marketing,Hyderabad,22.0,608796.0,1,6,6,2020-04-05,608796.0,Learner,High,MKT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,117,Pooja Malhotra,engineering,Kolkata,24.0,1011060.0,1,8,19,2021-12-05,1011060.0,Learner,High,NaN
84,102,Rahul Menon,Engineering,Hyderabad,38.0,1018440.0,11,6,15,2021-06-07,1018440.0,Experience candicate,High,ENG
88,124,Deepak Verma,Data Science,Hyderabad,41.0,1036560.0,9,7,8,2024-06-05,1036560.0,Experience candicate,High,NaN
4,145,Isha Nair,Data Science,Hyderabad,32.0,1058592.0,8,8,14,2019-11-25,1058592.0,Experience candicate,High,NaN
74,158,Tanvi Malhotra,HR,Mumbai,32.0,1060392.0,11,5,19,2021-02-26,1060392.0,Experience candicate,High,NaN

In [195]:
df.sort_values(by = "salary",ascending = False)

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_level,department_code
74,158,Tanvi Malhotra,HR,Mumbai,32.0,1060392.0,11,5,19,2021-02-26,1060392.0,Experience candicate,High,NaN
4,145,Isha Nair,Data Science,Hyderabad,32.0,1058592.0,8,8,14,2019-11-25,1058592.0,Experience candicate,High,NaN
88,124,Deepak Verma,Data Science,Hyderabad,41.0,1036560.0,9,7,8,2024-06-05,1036560.0,Experience candicate,High,NaN
84,102,Rahul Menon,Engineering,Hyderabad,38.0,1018440.0,11,6,15,2021-06-07,1018440.0,Experience candicate,High,ENG
39,117,Pooja Malhotra,engineering,Kolkata,24.0,1011060.0,1,8,19,2021-12-05,1011060.0,Learner,High,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,181,Karan Rao,Marketing,Hyderabad,22.0,608796.0,1,6,6,2020-04-05,608796.0,Learner,High,MKT
67,169,Swati Chatterjee,HR,Pune,33.0,597612.0,3,6,11,2021-08-20,597612.0,Learner,High,NaN
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,596316.0,0,4,7,2018-08-27,596316.0,Learner,High,MKT
36,167,Meera Malhotra,HR,Hyderabad,31.0,585864.0,4,5,4,2022-06-24,585864.0,Learner,High,NaN
26,141,Manish Kulkarni,HR,Chennai,27.0,550020.0,3,8,13,2022-07-21,550020.0,Learner,High,NaN

In [196]:
result = df.sort_values(by = ['department','salary'],ascending = [True,False])
result

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_level,department_code
16,177,Vivek Malhotra,Finance,Bangalore,30.861702,755634.0,3,4,12,2021-09-12,755634.0,Learner,High,NaN
27,162,Suresh Chatterjee,HR,Hyderabad,32.000000,711276.0,5,6,11,2020-09-05,711276.0,Learner,High,NaN
11,131,Priya Malhotra,Marketing,Hyderabad,25.000000,663540.0,1,7,12,2022-02-13,663540.0,Learner,High,NaN
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0,Experience candicate,High,NaN
88,124,Deepak Verma,Data Science,Hyderabad,41.000000,1036560.0,9,7,8,2024-06-05,1036560.0,Experience candicate,High,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,136,Sanjay Mehta,Sales,Hyderabad,30.000000,630876.0,5,7,8,2021-02-12,630876.0,Learner,High,NaN
5,140,Rahul Gupta,Sales,Hyderabad,23.000000,628848.0,0,9,13,2018-12-27,628848.0,Learner,High,NaN
39,117,Pooja Malhotra,engineering,Kolkata,24.000000,1011060.0,1,8,19,2021-12-05,1011060.0,Learner,High,NaN
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0,Learner,High,NaN
9,101,Ananya Malhotra,engineering,Hyderabad,24.000000,823092.0,2,8,0,2023-10-21,823092.0,Learner,High,NaN

In [197]:
df['department'].unique()

array(['Data Science', 'engineering', 'Engineering', 'Sales', 'HR',
       'Marketing', ' Marketing ', 'Finance', ' Finance ', ' HR ',
       'FINANCE', 'SALES', 'MARKETING'], dtype=object)

In [198]:
df['ddepartment'] = df['department'].str.strip().str.title()

In [199]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_level,department_code,ddepartment
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,848628.0,5,5,6,2021-07-02,848628.0,Learner,High,NaN,Data Science
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0,Learner,High,NaN,Engineering
2,171,Manish Desai,Data Science,Hyderabad,23.000000,838932.0,0,6,18,2019-04-24,838932.0,Learner,High,NaN,Data Science
3,146,Neha Das,Engineering,Pune,28.000000,839916.0,3,8,1,2022-12-13,839916.0,Learner,High,ENG,Engineering
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0,Experience candicate,High,NaN,Data Science

In [200]:
df['department'].unique()

array(['Data Science', 'engineering', 'Engineering', 'Sales', 'HR',
       'Marketing', ' Marketing ', 'Finance', ' Finance ', ' HR ',
       'FINANCE', 'SALES', 'MARKETING'], dtype=object)

In [201]:
result = df.sort_values(by = ['department','salary'],ascending = [True,False])
result

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_level,department_code,ddepartment
16,177,Vivek Malhotra,Finance,Bangalore,30.861702,755634.0,3,4,12,2021-09-12,755634.0,Learner,High,NaN,Finance
27,162,Suresh Chatterjee,HR,Hyderabad,32.000000,711276.0,5,6,11,2020-09-05,711276.0,Learner,High,NaN,Hr
11,131,Priya Malhotra,Marketing,Hyderabad,25.000000,663540.0,1,7,12,2022-02-13,663540.0,Learner,High,NaN,Marketing
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0,Experience candicate,High,NaN,Data Science
88,124,Deepak Verma,Data Science,Hyderabad,41.000000,1036560.0,9,7,8,2024-06-05,1036560.0,Experience candicate,High,NaN,Data Science
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,136,Sanjay Mehta,Sales,Hyderabad,30.000000,630876.0,5,7,8,2021-02-12,630876.0,Learner,High,NaN,Sales
5,140,Rahul Gupta,Sales,Hyderabad,23.000000,628848.0,0,9,13,2018-12-27,628848.0,Learner,High,NaN,Sales
39,117,Pooja Malhotra,engineering,Kolkata,24.000000,1011060.0,1,8,19,2021-12-05,1011060.0,Learner,High,NaN,Engineering
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0,Learner,High,NaN,Engineering
9,101,Ananya Malhotra,engineering,Hyderabad,24.000000,823092.0,2,8,0,2023-10-21,823092.0,Learner,High,NaN,Engineering

In [202]:
df["salary_rank"] = df["salary"].rank(ascending = False)

In [203]:
df.sort_values(by = "salary_rank")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_level,department_code,ddepartment,salary_rank
74,158,Tanvi Malhotra,HR,Mumbai,32.0,1060392.0,11,5,19,2021-02-26,1060392.0,Experience candicate,High,NaN,Hr,1.0
4,145,Isha Nair,Data Science,Hyderabad,32.0,1058592.0,8,8,14,2019-11-25,1058592.0,Experience candicate,High,NaN,Data Science,2.0
88,124,Deepak Verma,Data Science,Hyderabad,41.0,1036560.0,9,7,8,2024-06-05,1036560.0,Experience candicate,High,NaN,Data Science,3.0
84,102,Rahul Menon,Engineering,Hyderabad,38.0,1018440.0,11,6,15,2021-06-07,1018440.0,Experience candicate,High,ENG,Engineering,4.0
39,117,Pooja Malhotra,engineering,Kolkata,24.0,1011060.0,1,8,19,2021-12-05,1011060.0,Learner,High,NaN,Engineering,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,181,Karan Rao,Marketing,Hyderabad,22.0,608796.0,1,6,6,2020-04-05,608796.0,Learner,High,MKT,Marketing,92.0
67,169,Swati Chatterjee,HR,Pune,33.0,597612.0,3,6,11,2021-08-20,597612.0,Learner,High,NaN,Hr,93.0
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,596316.0,0,4,7,2018-08-27,596316.0,Learner,High,MKT,Marketing,94.0
36,167,Meera Malhotra,HR,Hyderabad,31.0,585864.0,4,5,4,2022-06-24,585864.0,Learner,High,NaN,Hr,95.0
26,141,Manish Kulkarni,HR,Chennai,27.0,550020.0,3,8,13,2022-07-21,550020.0,Learner,High,NaN,Hr,96.0

In [204]:
df.nlargest(5,"salary")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_level,department_code,ddepartment,salary_rank
74,158,Tanvi Malhotra,HR,Mumbai,32.0,1060392.0,11,5,19,2021-02-26,1060392.0,Experience candicate,High,NaN,Hr,1.0
4,145,Isha Nair,Data Science,Hyderabad,32.0,1058592.0,8,8,14,2019-11-25,1058592.0,Experience candicate,High,NaN,Data Science,2.0
88,124,Deepak Verma,Data Science,Hyderabad,41.0,1036560.0,9,7,8,2024-06-05,1036560.0,Experience candicate,High,NaN,Data Science,3.0
84,102,Rahul Menon,Engineering,Hyderabad,38.0,1018440.0,11,6,15,2021-06-07,1018440.0,Experience candicate,High,ENG,Engineering,4.0
39,117,Pooja Malhotra,engineering,Kolkata,24.0,1011060.0,1,8,19,2021-12-05,1011060.0,Learner,High,NaN,Engineering,5.0

In [205]:
df.nsmallest(5,"salary")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_level,department_code,ddepartment,salary_rank
26,141,Manish Kulkarni,HR,Chennai,27.0,550020.0,3,8,13,2022-07-21,550020.0,Learner,High,NaN,Hr,96.0
36,167,Meera Malhotra,HR,Hyderabad,31.0,585864.0,4,5,4,2022-06-24,585864.0,Learner,High,NaN,Hr,95.0
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,596316.0,0,4,7,2018-08-27,596316.0,Learner,High,MKT,Marketing,94.0
67,169,Swati Chatterjee,HR,Pune,33.0,597612.0,3,6,11,2021-08-20,597612.0,Learner,High,NaN,Hr,93.0
7,181,Karan Rao,Marketing,Hyderabad,22.0,608796.0,1,6,6,2020-04-05,608796.0,Learner,High,MKT,Marketing,92.0

In [206]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_level,department_code,ddepartment,salary_rank
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,848628.0,5,5,6,2021-07-02,848628.0,Learner,High,NaN,Data Science,26.0
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0,Learner,High,NaN,Engineering,13.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,838932.0,0,6,18,2019-04-24,838932.0,Learner,High,NaN,Data Science,28.0
3,146,Neha Das,Engineering,Pune,28.000000,839916.0,3,8,1,2022-12-13,839916.0,Learner,High,ENG,Engineering,27.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0,Experience candicate,High,NaN,Data Science,2.0

In [207]:
df['department'].nunique()

13

In [208]:
df['salary'].nunique()

89

In [209]:
df['city'].nunique()

7

In [210]:
df['salary'].nunique()

89

In [211]:
df.groupby('city')['age'].mean()

city
Bangalore    33.672340
Chennai      29.572340
Delhi        33.066285
Hyderabad    30.892857
Kolkata      28.000000
Mumbai       27.762411
Pune         31.642857
Name: age, dtype: float64

In [212]:
df.groupby('city')['salary'].max()

city
Bangalore     973344.0
Chennai       926664.0
Delhi         964296.0
Hyderabad    1058592.0
Kolkata      1011060.0
Mumbai       1060392.0
Pune          942540.0
Name: salary, dtype: float64

In [215]:
df.groupby(['city','department'])['salary'].max()

city       department
Bangalore   Finance         755634.0
           Data Science     874344.0
           Engineering      973344.0
           Finance          852744.0
           HR               894060.0
           Marketing        762888.0
Chennai    Engineering      926664.0
           FINANCE          862668.0
           HR               627000.0
           MARKETING        668880.0
           Marketing        755634.0
           Sales            694296.0
Delhi      Data Science     915204.0
           Engineering      964296.0
           Finance          797064.0
           HR               796356.0
           Marketing        833988.0
           Sales            821880.0
Hyderabad   HR              711276.0
            Marketing       663540.0
           Data Science    1058592.0
           Engineering     1018440.0
           Finance          967164.0
           HR               828912.0
           Marketing        748716.0
           SALES            752760.0
           Sales            755634.0
           engineering      823092.0
Kolkata    Data Science     917100.0
           Engineering      902712.0
           Finance          713064.0
           HR               716316.0
           Marketing        710232.0
           Sales            720180.0
           engineering     1011060.0
Mumbai     Data Science     941580.0
           Engineering      755634.0
           Finance          769344.0
           HR              1060392.0
           Marketing        779328.0
           Sales            634344.0
           engineering      924696.0
Pune       Data Science     905976.0
           Engineering      942540.0
           Finance          744240.0
           HR               818364.0
           Marketing        746724.0
Name: salary, dtype: float64

In [216]:
df.groupby(['city','department'])['salary'].max()

city       department
Bangalore   Finance         755634.0
           Data Science     874344.0
           Engineering      973344.0
           Finance          852744.0
           HR               894060.0
           Marketing        762888.0
Chennai    Engineering      926664.0
           FINANCE          862668.0
           HR               627000.0
           MARKETING        668880.0
           Marketing        755634.0
           Sales            694296.0
Delhi      Data Science     915204.0
           Engineering      964296.0
           Finance          797064.0
           HR               796356.0
           Marketing        833988.0
           Sales            821880.0
Hyderabad   HR              711276.0
            Marketing       663540.0
           Data Science    1058592.0
           Engineering     1018440.0
           Finance          967164.0
           HR               828912.0
           Marketing        748716.0
           SALES            752760.0
           Sales            755634.0
           engineering      823092.0
Kolkata    Data Science     917100.0
           Engineering      902712.0
           Finance          713064.0
           HR               716316.0
           Marketing        710232.0
           Sales            720180.0
           engineering     1011060.0
Mumbai     Data Science     941580.0
           Engineering      755634.0
           Finance          769344.0
           HR              1060392.0
           Marketing        779328.0
           Sales            634344.0
           engineering      924696.0
Pune       Data Science     905976.0
           Engineering      942540.0
           Finance          744240.0
           HR               818364.0
           Marketing        746724.0
Name: salary, dtype: float64

In [217]:
df.groupby(['city','department'])['salary'].max()

city       department
Bangalore   Finance         755634.0
           Data Science     874344.0
           Engineering      973344.0
           Finance          852744.0
           HR               894060.0
           Marketing        762888.0
Chennai    Engineering      926664.0
           FINANCE          862668.0
           HR               627000.0
           MARKETING        668880.0
           Marketing        755634.0
           Sales            694296.0
Delhi      Data Science     915204.0
           Engineering      964296.0
           Finance          797064.0
           HR               796356.0
           Marketing        833988.0
           Sales            821880.0
Hyderabad   HR              711276.0
            Marketing       663540.0
           Data Science    1058592.0
           Engineering     1018440.0
           Finance          967164.0
           HR               828912.0
           Marketing        748716.0
           SALES            752760.0
           Sales            755634.0
           engineering      823092.0
Kolkata    Data Science     917100.0
           Engineering      902712.0
           Finance          713064.0
           HR               716316.0
           Marketing        710232.0
           Sales            720180.0
           engineering     1011060.0
Mumbai     Data Science     941580.0
           Engineering      755634.0
           Finance          769344.0
           HR              1060392.0
           Marketing        779328.0
           Sales            634344.0
           engineering      924696.0
Pune       Data Science     905976.0
           Engineering      942540.0
           Finance          744240.0
           HR               818364.0
           Marketing        746724.0
Name: salary, dtype: float64

In [218]:
df.groupby("department")[["salary","performance_score"]].mean()

                     salary  performance_score
department
 Finance      755634.000000           4.000000
 HR           711276.000000           6.000000
 Marketing    663540.000000           7.000000
Data Science  917409.600000           5.700000
Engineering   881781.857143           5.214286
FINANCE       862668.000000           5.000000
Finance       792266.000000           5.400000
HR            714429.913043           5.695652
MARKETING     668880.000000           5.000000
Marketing     718039.764706           5.882353
SALES         752760.000000           7.000000
Sales         706307.250000           6.500000
engineering   919616.000000           8.000000

In [219]:
df.groupby("department").agg({
    "salary":["mean","max"],
    "performance_score":"mean",
    "employee_id":"count"
})

                     salary            performance_score employee_id
                       mean        max              mean       count
department
 Finance      755634.000000   755634.0          4.000000           1
 HR           711276.000000   711276.0          6.000000           1
 Marketing    663540.000000   663540.0          7.000000           1
Data Science  917409.600000  1058592.0          5.700000          10
Engineering   881781.857143  1018440.0          5.214286          14
FINANCE       862668.000000   862668.0          5.000000           1
Finance       792266.000000   967164.0          5.400000          15
HR            714429.913043  1060392.0          5.695652          23
MARKETING     668880.000000   668880.0          5.000000           1
Marketing     718039.764706   833988.0          5.882353          17
SALES         752760.000000   752760.0          7.000000           1
Sales         706307.250000   821880.0          6.500000           8
engineering   919616.000000  1011060.0          8.000000           3

In [224]:
department_summary = df.groupby("department").agg(
    average_salary=("salary", "mean"),
    highest_salary=("salary", "max"),
    employee_count=("employee_id", "count")
)

In [225]:
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_level,department_code,ddepartment,salary_rank
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,848628.0,5,5,6,2021-07-02,848628.0,Learner,High,NaN,Data Science,26.0
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,924696.0,1,8,8,2024-02-05,924696.0,Learner,High,NaN,Engineering,13.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,838932.0,0,6,18,2019-04-24,838932.0,Learner,High,NaN,Data Science,28.0
3,146,Neha Das,Engineering,Pune,28.000000,839916.0,3,8,1,2022-12-13,839916.0,Learner,High,ENG,Engineering,27.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,1058592.0,8,8,14,2019-11-25,1058592.0,Experience candicate,High,NaN,Data Science,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.000000,668880.0,0,5,22,2020-04-22,668880.0,Learner,High,NaN,Marketing,82.0
96,172,Neha Desai,HR,Chennai,22.000000,627000.0,0,5,7,2020-11-14,627000.0,Learner,High,NaN,Hr,90.0
97,115,Neha Reddy,Marketing,Chennai,43.000000,755634.0,12,4,10,2019-06-06,755634.0,Experience candicate,High,MKT,Marketing,48.5
98,193,Priya Nayak,HR,Hyderabad,23.000000,681852.0,3,9,16,2019-08-07,681852.0,Learner,High,NaN,Hr,76.0
99,152,Kavya Joshi,Marketing,Delhi,44.000000,833988.0,10,7,4,2022-03-25,833988.0,Experience candicate,High,MKT,Marketing,30.0